AllCops:
  NewCops: enable
  ActiveSupportExtensionsEnabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HeredocIndentation:
  Enabled: true

Layout/LineLength:
  Max: 130
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Alias:
  Enabled: false

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false

Style/BlockDelimiters:
  AllowedPatterns: ['expect']

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/EmptyLambdaParameter:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

# Adds underscores in between every 3 zeros i.e. 10_000_000
Style/NumericLiterals:
  Enabled: false
  AllowedNumbers: ['d4'] # only start applying after 9,999

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: false
  # EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
  # EnforcedStyle: brackets
